"""...

Revision ID: 4520b9703b95
Revises: 16e61ea3dcf1
Create Date: 2026-07-12 14:33:55.121217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4520b9703b95'
down_revision: Union[str, Sequence[str], None] = '16e61ea3dcf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_queries',
    sa.Column('query_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('book_id', sa.String(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('response_text', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('query_id')
    )
    op.create_index(op.f('ix_user_queries_book_id'), 'user_queries', ['book_id'], unique=False)
    op.create_index(op.f('ix_user_queries_user_id'), 'user_queries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_queries_user_id'), table_name='user_queries')
    op.drop_index(op.f('ix_user_queries_book_id'), table_name='user_queries')
    op.drop_table('user_queries')
    # ### end Alembic commands ###
