"""create books and chapters

Revision ID: 6d84cee6cd25
Revises: 4fa701a0d3f7
Create Date: 2026-06-19 13:38:37.832039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d84cee6cd25'
down_revision: Union[str, Sequence[str], None] = '4fa701a0d3f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('page_id', sa.String(), nullable=False),
    sa.Column('book_id', sa.String(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('page_id')
    )
    op.create_index(op.f('ix_pages_book_id'), 'pages', ['book_id'], unique=False)
    op.create_index(op.f('ix_pages_page_number'), 'pages', ['page_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pages_page_number'), table_name='pages')
    op.drop_index(op.f('ix_pages_book_id'), table_name='pages')
    op.drop_table('pages')
    # ### end Alembic commands ###
